version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  version: 3.10
  install:
    - method: pip
      path: .
    - requirements: pyproject.toml
      method: poetry

sphinx:
  configuration: docs/conf.py
