name: Python UnitTests

on:
 push:
    branches: [ master ]
 pull_request:
    branches: [ master ]

jobs:
 build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install poetry
      run: |
        python -m pip install poetry

    - name: Configure poetry
      run: |
        python -m poetry config virtualenvs.in-project true

    - name: Cache the virtualenv
      uses: actions/cache@v2
      with:
        path: ./.venv
        key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      run: |
        python -m poetry install

    - name: Run tests
      run: |
        mkdir logs
        python -m poetry run python -m unittest tests/test_tests.py
